# Embedding A/B checklist (no production re-embed)
Write-Host "EMPIRE Embedding A/B"
Write-Host "Production embedder: nomic-embed-text (do not change cognee.env yet)"
Write-Host ""
Write-Host "Fixture eval (recommended first):"
Write-Host "  .\scripts\embedding-ab.ps1 status"
Write-Host "  .\scripts\embedding-ab.ps1 pull    # optional qwen3-embedding:0.6b"
Write-Host "  .\scripts\embedding-ab.ps1 eval"
Write-Host ""
Write-Host "Optional Cognee trial (Architect approval only):"
Write-Host "1) Create dataset embed_ab_test only"
Write-Host "2) Ingest a tiny fixture set with trial embed model"
Write-Host "3) Compare recall vs eve_core / primitives_test"
Write-Host "4) Architect approves before any eve_memory re-embed"
Write-Host ""
Write-Host "See docs/EMBEDDING_AB.md"
