#Requires -Version 5.1
<#
.SYNOPSIS
  Create the EMPIRE Disassembly Catalog whiteboard and write config/heptabase.env
#>
param(
  [switch]$SeedLegend
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $Root "config\heptabase.env"
$Example = Join-Path $Root "config\heptabase.env.example"
$Py = Join-Path $Root "venv\Scripts\python.exe"

function Resolve-HeptabaseCli {
  if ($env:HEPTABASE_CLI_PATH -and (Test-Path $env:HEPTABASE_CLI_PATH)) {
    return $env:HEPTABASE_CLI_PATH
  }
  $local = Join-Path $env:LOCALAPPDATA ".heptabase\bin\heptabase.cmd"
  if (Test-Path $local) { return $local }
  $cmd = Get-Command heptabase -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  throw "Heptabase CLI not found. Enable Local CLI in the Heptabase desktop app."
}

$cli = Resolve-HeptabaseCli
Write-Host "Using CLI: $cli"
& $cli --version
if ($LASTEXITCODE -ne 0) {
  throw "Heptabase CLI failed. Start the Heptabase desktop app and retry."
}

$createJson = & $cli whiteboard create --title "EMPIRE Disassembly Catalog" 2>&1
if ($LASTEXITCODE -ne 0) {
  throw "whiteboard create failed: $createJson"
}
$parsed = $createJson | ConvertFrom-Json
$wbId = $parsed.whiteboardId
if (-not $wbId) { $wbId = $parsed.id }
if (-not $wbId) {
  throw "Could not parse whiteboard id from: $createJson"
}

$content = @"
# Generated by ensure-heptabase-disassembly-board.ps1 on $(Get-Date -Format o)
HEPTABASE_DISASSEMBLY_WHITEBOARD_ID=$wbId
HEPTABASE_CLI_PATH=$cli
"@
Set-Content -Path $EnvFile -Value $content -Encoding utf8
Write-Host "Wrote $EnvFile with whiteboard id $wbId"

if ($SeedLegend) {
  if (-not (Test-Path $Py)) { throw "Python venv missing at $Py" }
  & $Py -m pipeline.disassembly_publish seed-legend --architect-confirm
  if ($LASTEXITCODE -ne 0) {
    Write-Warning "Legend seed failed — you can rerun: python -m pipeline.disassembly_publish seed-legend --architect-confirm"
  }
}

Write-Host "Done. Open the board in Heptabase or call heptabase_whiteboard_structure from Eve."
