#!/usr/bin/env python3
"""Harvest Architect phrasing from Obsidian SBX_Vault (+ optional RESYNC).

Every line is tagged by provenance so Eve does not mimic Gemini or uploads as
"how the Architect talks."

  .\\venv\\Scripts\\python.exe scripts\\harvest-architect-voice-from-vault.py
  .\\venv\\Scripts\\python.exe scripts\\harvest-architect-voice-from-vault.py --dry-run

Env:
  EMPIRE_SBX_VAULT — default SBX path (OneDrive Desktop)
  EMPIRE_VAULT_PATHS — semicolon list; first existing root wins unless --vault set
"""

from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import Enum
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "data" / "curated_primitives" / "raw_materials" / "architect-vault-voice-supplement.md"

DEFAULT_SBX = Path(
    os.environ.get(
        "EMPIRE_SBX_VAULT",
        r"C:\Users\m69nr\OneDrive\Desktop\SBX_Vault",
    )
)
DEFAULT_VAULTS = [
    DEFAULT_SBX,
    Path(r"C:\Users\m69nr\OneDrive\Documents\RESYNC_2026"),
    Path(r"C:\Users\m69nr\Documents\RESYNC_2026"),
    Path(r"I:\01_notes_T7\RESYNC_2026_obsidian_live"),
    Path(r"I:\01_notes_T7\SBX_Vault_obsidian_earlier"),
]

GEMINI_URL = re.compile(r"https?://gemini\.google\.com/", re.I)
FRONTMATTER_END = re.compile(r"^---\s*$", re.M)
USER_LINE = re.compile(
    r"^(?:\*\*You\*\*|You:|>\s*(?:You|User)[:\s]|>\s*I(?:'m| am| have| need| want| feel| decided)|me:)",
    re.I,
)
FIRST_PERSON = re.compile(
    r"\b(I(?:'m| am| have| need| want| feel| decided| realized| been| was| ended up)|help me|can you|how do I)\b",
    re.I,
)
MODEL_START = re.compile(
    r"^(Custom Gem|LEGO:|Phase \d:|Here is the|Here'?s the|The Council|### Phase|\*\*\d+\\.)",
    re.I,
)
EXPORT_NAME = re.compile(r"(notie export|notes export|export date:)", re.I)
LINE_SKIP = re.compile(
    r"^(Hello! I am Lexicon|When the user starts a session|IF user says:|"
    r"To ensure I give you the most practical|Let's dive into the Listening Guide)",
    re.I,
)
SONG_LIST_LINE = re.compile(r"^\d+\.\s+[\w\s'.()]+\s-\s+", re.I)
LEXICON_HEAVY = re.compile(r"I am Lexicon", re.I)
PROMPT_TEMPLATE = re.compile(r"when the user starts|IF user says", re.I)


class Provenance(str, Enum):
    ARCHITECT_AUTHOR = "architect_author"
    GEMINI_USER_TURN = "gemini_user_turn"
    UPLOADED_EXPORT = "uploaded_export"
    THIRD_PARTY = "third_party_reference"
    MODEL_GENERATED = "model_generated"


@dataclass(frozen=True)
class TaggedLine:
    text: str
    provenance: Provenance
    source_note: str


def resolve_vaults(explicit: list[str] | None) -> list[Path]:
    if explicit:
        return [Path(p) for p in explicit]
    env = os.environ.get("EMPIRE_VAULT_PATHS", "")
    if env.strip():
        return [Path(p.strip()) for p in env.split(";") if p.strip()]
    return DEFAULT_VAULTS


def strip_frontmatter(text: str) -> str:
    if not text.startswith("---"):
        return text
    parts = FRONTMATTER_END.split(text, maxsplit=2)
    if len(parts) >= 3:
        return parts[2].lstrip("\n")
    return text


def is_gemini_clipping(text: str, path: Path) -> bool:
    head = text[:4000].casefold()
    if GEMINI_URL.search(text):
        return True
    if 'title: "google gemini"' in head or "title: google gemini" in head:
        return True
    name = path.name.casefold()
    if "gemini" in name and ("convo" in name or "whole convo" in name or "google gemini" in name):
        return True
    if "clippings" in str(path).casefold() and ("gemini" in name or GEMINI_URL.search(text)):
        return True
    return False


def is_model_script(path: Path, text: str) -> bool:
    name = path.name.casefold()
    if "claude report" in name or "supplemental claude" in name:
        return True
    if "notegpt" in name or "zet god script" in name:
        return True
    if "gemini genie" in name and "clippings" not in str(path).casefold():
        return False
    head = text[:1500].casefold()
    return "generated by" in head and "architect" not in head


def is_uploaded_export(path: Path, text: str) -> bool:
    name = path.name.casefold()
    if EXPORT_NAME.search(name) or EXPORT_NAME.search(text[:500]):
        return True
    if "notie ai - notes export" in text[:800].casefold():
        return True
    return False


def classify_note(path: Path, text: str) -> Provenance:
    if is_model_script(path, text):
        return Provenance.MODEL_GENERATED
    if is_uploaded_export(path, text):
        return Provenance.UPLOADED_EXPORT
    if is_gemini_clipping(text, path):
        return Provenance.GEMINI_USER_TURN
    body = strip_frontmatter(text)
    if LEXICON_HEAVY.search(body) and body.lower().count("i am lexicon") >= 2:
        return Provenance.THIRD_PARTY
    if PROMPT_TEMPLATE.search(body[:5000]):
        return Provenance.THIRD_PARTY
    rel = str(path).casefold()
    if "clippings" in rel or "zettelkasten" in rel:
        if FIRST_PERSON.search(text[:3000]):
            return Provenance.ARCHITECT_AUTHOR
        return Provenance.THIRD_PARTY
    if FIRST_PERSON.search(text[:4000]):
        return Provenance.ARCHITECT_AUTHOR
    return Provenance.THIRD_PARTY


def extract_gemini_user_preamble(body: str) -> list[str]:
    lines: list[str] = []
    for raw in body.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if MODEL_START.match(line):
            break
        if len(line) < 10 or len(line) > 320:
            continue
        if FIRST_PERSON.search(line) or line.endswith("?"):
            lines.append(line)
        elif USER_LINE.match(line):
            cleaned = re.sub(r"^(?:\*\*You\*\*|You:|me:)\s*", "", line, flags=re.I).strip()
            if cleaned:
                lines.append(cleaned)
    return lines


def extract_author_lines(body: str) -> list[str]:
    lines: list[str] = []
    for raw in body.splitlines():
        line = raw.strip()
        if len(line) < 12 or len(line) > 280:
            continue
        if line.startswith("#"):
            continue
        if LINE_SKIP.match(line):
            continue
        if SONG_LIST_LINE.match(line) and not re.search(r"\b(I|my|me)\b", line[:60], re.I):
            continue
        if FIRST_PERSON.search(line) or USER_LINE.match(line):
            lines.append(line.lstrip("-* ").strip())
    return lines


def harvest_vault(root: Path, max_files: int = 2000) -> dict[str, object]:
    buckets: dict[Provenance, list[TaggedLine]] = {p: [] for p in Provenance}
    scanned = 0
    skipped_model = 0

    for path in sorted(root.rglob("*.md")):
        if scanned >= max_files:
            break
        if ".obsidian" in path.parts:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        scanned += 1
        rel = path.relative_to(root).as_posix()
        kind = classify_note(path, text)
        if kind is Provenance.MODEL_GENERATED:
            skipped_model += 1
            continue

        body = strip_frontmatter(text)
        if kind is Provenance.GEMINI_USER_TURN:
            for line in extract_gemini_user_preamble(body):
                buckets[Provenance.GEMINI_USER_TURN].append(
                    TaggedLine(line, Provenance.GEMINI_USER_TURN, rel)
                )
            continue

        if kind is Provenance.UPLOADED_EXPORT:
            for line in extract_author_lines(body):
                buckets[Provenance.UPLOADED_EXPORT].append(
                    TaggedLine(line, Provenance.UPLOADED_EXPORT, rel)
                )
            continue

        if kind is Provenance.ARCHITECT_AUTHOR:
            for line in extract_author_lines(body):
                buckets[Provenance.ARCHITECT_AUTHOR].append(
                    TaggedLine(line, Provenance.ARCHITECT_AUTHOR, rel)
                )
            continue

        # third_party: skip line harvest (titles only in stats)

    return {
        "buckets": buckets,
        "files_scanned": scanned,
        "skipped_model_scripts": skipped_model,
    }


def dedupe_tagged(items: list[TaggedLine], limit: int) -> list[TaggedLine]:
    seen: set[str] = set()
    out: list[TaggedLine] = []
    for item in items:
        key = item.text.casefold()
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
        if len(out) >= limit:
            break
    return out


def provenance_key_block() -> str:
    return """## Provenance key (read before mimicking voice)

| Tag | Meaning for Eve |
|-----|-----------------|
| **architect_author** | Raine wrote the note (daily, EVOLVE, Gadget, personal). **Primary voice** — match cadence and goals. |
| **gemini_user_turn** | His **prompt** inside a Gemini Web Clipper export — use for **intent/routing**, not tone (model reply is discarded). |
| **uploaded_export** | App export (Notie, etc.) — **his words**, situational journal; good for context, not tool names. |
| **third_party_reference** | Clippings, Zet library, reference — **not his voice**; do not style replies like these. |
| **model_generated** | Gemini/Claude/NoteGPT scripts — **context only**, never quoted as how he talks. |

Default vault: `C:\\Users\\m69nr\\OneDrive\\Desktop\\SBX_Vault` (may be incomplete vs RESYNC_2026; still authoritative for his phrasing).
"""


def static_digest_block() -> str:
    return """## Static digest (Mechanic — vault audit summary)

See `docs/audits/2026-09-28-vault-and-dialogue-digest.md` for timeline. Codex JSON remains authoritative for routing.
"""


def format_section(title: str, items: list[TaggedLine], limit: int) -> list[str]:
    picked = dedupe_tagged(items, limit)
    lines = [f"### {title}", ""]
    if not picked:
        lines.append("- _(none extracted)_")
        return lines
    for item in picked:
        lines.append(f"- [{item.provenance.value}] {item.text}")
    return lines


def write_output(vault_used: Path | None, harvest: dict[str, object] | None) -> None:
    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    parts = [
        "---",
        "title: Architect vault and Gemini dialogue voice (supplement)",
        "dataset: eve_memory",
        "fuel: architect_voice",
        "companion: architect-intent-vocabulary.md",
        f"generated: {ts}",
        "---",
        "",
        "# Vault + Gemini — Architect phrasing (supplement)",
        "",
        "Eve: recall with `architect-intent-vocabulary.md` and `architect-eve-language-bridge.md`. "
        "**Only `architect_author` and selective `uploaded_export` lines define how he talks.** "
        "`gemini_user_turn` = what he *asked*, not how Eve should sound.",
        "",
        provenance_key_block(),
        static_digest_block(),
    ]

    if vault_used and harvest:
        buckets: dict[Provenance, list[TaggedLine]] = harvest["buckets"]  # type: ignore[assignment]
        parts.extend(
            [
                "",
                f"## Live harvest from `{vault_used}`",
                "",
                f"Files scanned: {harvest['files_scanned']}. "
                f"Model scripts skipped: {harvest['skipped_model_scripts']}.",
                "",
            ]
        )
        parts.extend(format_section("Architect author (primary voice)", buckets[Provenance.ARCHITECT_AUTHOR], 70))
        parts.append("")
        parts.extend(format_section("Uploaded exports (his words, journal context)", buckets[Provenance.UPLOADED_EXPORT], 35))
        parts.append("")
        parts.extend(format_section("Gemini clippings (user turns only — not model text)", buckets[Provenance.GEMINI_USER_TURN], 35))
    else:
        parts.extend(
            [
                "",
                "## Live harvest",
                "",
                "Vault not found. Set `EMPIRE_SBX_VAULT` or `--vault`, then re-run.",
                "",
            ]
        )

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(parts) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Harvest Architect voice from Obsidian vaults")
    parser.add_argument("--vault", action="append", dest="vaults", help="Vault root (repeatable)")
    parser.add_argument("--dry-run", action="store_true", help="Print stats only")
    args = parser.parse_args()

    candidates = resolve_vaults(args.vaults)
    vault_used: Path | None = None
    harvest: dict[str, object] | None = None
    for candidate in candidates:
        if candidate.is_dir():
            vault_used = candidate
            harvest = harvest_vault(candidate)
            break

    if args.dry_run:
        counts = {}
        if harvest:
            buckets = harvest["buckets"]
            counts = {k.value: len(v) for k, v in buckets.items()}  # type: ignore[union-attr]
        print(
            json.dumps(
                {
                    "vault": str(vault_used) if vault_used else None,
                    "files_scanned": harvest["files_scanned"] if harvest else 0,
                    "line_counts": counts,
                },
                indent=2,
            )
        )
        return 0

    write_output(vault_used, harvest)
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}")
    if not vault_used:
        print("Warning: no vault found — output contains provenance key + static digest only.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
